' automatically generated by the FlatBuffers compiler, do not modify
'
' *  ******************************************************************************
' *  *
' *  *
' *  * This program and the accompanying materials are made available under the
' *  * terms of the Apache License, Version 2.0 which is available at
' *  * https://www.apache.org/licenses/LICENSE-2.0.
' *  *
' *  *  See the NOTICE file distributed with this work for additional
' *  *  information regarding copyright ownership.
' *  * Unless required by applicable law or agreed to in writing, software
' *  * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
' *  * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
' *  * License for the specific language governing permissions and limitations
' *  * under the License.
' *  *
' *  * SPDX-License-Identifier: Apache-2.0
' *  *****************************************************************************
' 
Namespace org.nd4j.graph

	Public NotInheritable Class DType
	  Private Sub New()
	  End Sub
	  Public Const INHERIT As SByte = 0
	  Public Const BOOL As SByte = 1
	  Public Const FLOAT8 As SByte = 2
	  Public Const HALF As SByte = 3
	  Public Const HALF2 As SByte = 4
	  Public Const FLOAT As SByte = 5
	  Public Const [DOUBLE] As SByte = 6
	  Public Const INT8 As SByte = 7
	  Public Const INT16 As SByte = 8
	  Public Const INT32 As SByte = 9
	  Public Const INT64 As SByte = 10
	  Public Const UINT8 As SByte = 11
	  Public Const UINT16 As SByte = 12
	  Public Const UINT32 As SByte = 13
	  Public Const UINT64 As SByte = 14
	  Public Const QINT8 As SByte = 15
	  Public Const QINT16 As SByte = 16
	  Public Const BFLOAT16 As SByte = 17
	  Public Const UTF8 As SByte = 50
	  Public Const UTF16 As SByte = 51
	  Public Const UTF32 As SByte = 52

	  Public Shared ReadOnly names() As String = { "INHERIT", "BOOL", "FLOAT8", "HALF", "HALF2", "FLOAT", "DOUBLE", "INT8", "INT16", "INT32", "INT64", "UINT8", "UINT16", "UINT32", "UINT64", "QINT8", "QINT16", "BFLOAT16", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "UTF8", "UTF16", "UTF32"}

	  Public Shared Function name(ByVal e As Integer) As String
		  Return names(e)
	  End Function
	End Class


End Namespace