Imports com.google.flatbuffers

' automatically generated by the FlatBuffers compiler, do not modify
'
' *  ******************************************************************************
' *  *
' *  *
' *  * This program and the accompanying materials are made available under the
' *  * terms of the Apache License, Version 2.0 which is available at
' *  * https://www.apache.org/licenses/LICENSE-2.0.
' *  *
' *  *  See the NOTICE file distributed with this work for additional
' *  *  information regarding copyright ownership.
' *  * Unless required by applicable law or agreed to in writing, software
' *  * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
' *  * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
' *  * License for the specific language governing permissions and limitations
' *  * under the License.
' *  *
' *  * SPDX-License-Identifier: Apache-2.0
' *  *****************************************************************************
' 
Namespace org.nd4j.graph

'JAVA TO VB CONVERTER TODO TASK: Most Java annotations will not have direct .NET equivalent attributes:
'ORIGINAL LINE: @SuppressWarnings("unused") public final class FlatDropRequest extends Table
	Public NotInheritable Class FlatDropRequest
		Inherits Table

	  Public Shared Function getRootAsFlatDropRequest(ByVal _bb As ByteBuffer) As FlatDropRequest
		  Return getRootAsFlatDropRequest(_bb, New FlatDropRequest())
	  End Function
	  Public Shared Function getRootAsFlatDropRequest(ByVal _bb As ByteBuffer, ByVal obj As FlatDropRequest) As FlatDropRequest
		  _bb.order(ByteOrder.LITTLE_ENDIAN)
		  Return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
	  End Function
	  Public Sub __init(ByVal _i As Integer, ByVal _bb As ByteBuffer)
		  bb_pos = _i
		  bb = _bb
		  vtable_start = bb_pos - bb.getInt(bb_pos)
		  vtable_size = bb.getShort(vtable_start)
	  End Sub
	  Public Function __assign(ByVal _i As Integer, ByVal _bb As ByteBuffer) As FlatDropRequest
		  __init(_i, _bb)
		  Return Me
	  End Function

	  Public Function id() As Long
		  Dim o As Integer = __offset(4)
		  Return If(o <> 0, bb.getLong(o + bb_pos), 0L)
	  End Function

	  Public Shared Function createFlatDropRequest(ByVal builder As FlatBufferBuilder, ByVal id As Long) As Integer
		builder.startObject(1)
		FlatDropRequest.addId(builder, id)
		Return FlatDropRequest.endFlatDropRequest(builder)
	  End Function

	  Public Shared Sub startFlatDropRequest(ByVal builder As FlatBufferBuilder)
		  builder.startObject(1)
	  End Sub
	  Public Shared Sub addId(ByVal builder As FlatBufferBuilder, ByVal id As Long)
		  builder.addLong(0, id, 0L)
	  End Sub
	  Public Shared Function endFlatDropRequest(ByVal builder As FlatBufferBuilder) As Integer
		Dim o As Integer = builder.endObject()
		Return o
	  End Function
	End Class


End Namespace