Imports ComputationGraphConfiguration = org.deeplearning4j.nn.conf.ComputationGraphConfiguration

'
' *  ******************************************************************************
' *  *
' *  *
' *  * This program and the accompanying materials are made available under the
' *  * terms of the Apache License, Version 2.0 which is available at
' *  * https://www.apache.org/licenses/LICENSE-2.0.
' *  *
' *  *  See the NOTICE file distributed with this work for additional
' *  *  information regarding copyright ownership.
' *  * Unless required by applicable law or agreed to in writing, software
' *  * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
' *  * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
' *  * License for the specific language governing permissions and limitations
' *  * under the License.
' *  *
' *  * SPDX-License-Identifier: Apache-2.0
' *  *****************************************************************************
' 

Namespace org.deeplearning4j.nn.conf.module

	Public Interface GraphBuilderModule

		''' <summary>
		''' A module should return its name. Useful for automatically generating layer names.
		''' 
		''' @note Convention is to define module names that are entirely lowercase for the purpose of generating layer names.
		''' </summary>
		''' <returns> The module name as a string. </returns>
		ReadOnly Property ModuleName As String

		''' <summary>
		''' Add a layer to the collection of layers being generated by this module.
		''' </summary>
		''' <param name="graph"> </param>
		''' <param name="layerName"> </param>
		''' <param name="inputSize"> </param>
		''' <param name="config"> </param>
		''' <param name="inputLayer">
		''' </param>
		''' <returns> An instance of GraphBuilder with appended layers. </returns>
		Function updateBuilder(ByVal graph As ComputationGraphConfiguration.GraphBuilder, ByVal layerName As String, ByVal inputSize As Integer, ByVal config()() As Integer, ByVal inputLayer As String) As ComputationGraphConfiguration.GraphBuilder


	End Interface

End Namespace